What is the capital of {stateOrCountry}? Respond with the following format:
           The capital of ```stateOrCountry``` is ```capital```.
           The city has a current population of ```population```.
           The highest historical population recorded was ```maxHistoricalPopulation```.
           The city is located in ```region```.
           The average annual temperature is ```averageTemperature```°C.
           The priamry language spoken is ```language```.
           The currency used is ```currency```.
           An interesting fact about is ```interestingFact```.